// cz.config.js
/** @type {import('cz-git').CommitizenGitOptions} */
module.exports = {
    alias: { fd: 'docs: fix typos   XXXX' },
    messages: {
        type: 'Select the type of change that you\'re committing:',
        // scope: ['Denote the SCOPE of this change (optional):'],
        // customScope: 'Denote the SCOPE of this change:',
        // subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
        // body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
        // breaking: 'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
        // footerPrefixsSelect: 'Select the ISSUES type of changeList by this change (optional):',
        // customFooterPrefixs: 'Input ISSUES prefix:',
        // footer: 'List any ISSUES by this change. E.g.: #31, #34:\n',
        confirmCommit: 'Are you sure you want to proceed with the commit above?'
    },
    types: [
        { value: "feat", name: "✨ （功能版本更新） A new feature", emoji: ":sparkles:" },
        { value: "fix", name: "🐛 （bug修复） A bug fix", emoji: ":bug:" },
        { value: "hotfix", name: "🐛 （补丁修复）A bug fix", emoji: ":bug:" },
        { value: "style", name: "💄 （样式调整）Style changes", emoji: ":lipstick:" },
        { value: "perf", name: "⚡️（性能优化）Improves performance", emoji: ":zap:" },
        { value: "revert", name: "⏪️（版本回滚）Reverts a previous commit ", emoji: ":rewind:" },
        { value: "docs", name: "📝 （文档更新）Documentation changes ", emoji: ":memo:" },
        { value: "refactor", name: "♻️（重构）refactor", emoji: ":recycle:" },
        { value: "other", name: "📝 （其他）other changes ", emoji: ":rewind:" },

        // { value: "feat", name: "feat:     ✨  A new feature", emoji: ":sparkles:" },
        // { value: "fix", name: "fix:      🐛  A bug fix", emoji: ":bug:" },
        // { value: "docs", name: "docs:     📝  Documentation only changes", emoji: ":memo:" },
        // { value: "style", name: "style:    💄  Changes that do not affect the meaning of the code", emoji: ":lipstick:" },
        // { value: "refactor", name: "refactor: ♻️   A code change that neither fixes a bug nor adds a feature", emoji: ":recycle:" },
        // { value: "perf", name: "perf:     ⚡️  A code change that improves performance", emoji: ":zap:" },
        // { value: "test", name: "test:     ✅  Adding missing tests or correcting existing tests", emoji: ":white_check_mark:" },
        // { value: "build", name: "build:    📦️   Changes that affect the build system or external dependencies", emoji: ":package:" },
        // { value: "ci", name: "ci:       🎡  Changes to our CI configuration files and scripts", emoji: ":ferris_wheel:" },
        // { value: "chore", name: "chore:    🔨  Other changes that don't modify src or test files", emoji: ":hammer:" },
        // { value: "revert", name: "revert:   ⏪️  Reverts a previous commit", emoji: ":rewind:" }
    ],
    useEmoji: true,
    emojiAlign: "center",
    themeColorCode: "",
    scopes: [
        { value: 'Permission', name: '权限管理' },
        { value: 'PDMS', name: 'PDMS' },
        { value: 'XML', name: 'XML' },
        { value: 'PRMS', name: 'PRMS' },
        { value: 'Gadgets', name: 'Gadgets' },
        { value: 'FVM', name: '版本管理' },
        { value: 'GPMS', name: 'GPMS' },
        { value: 'PRPS', name: 'PRPS' },
        { value: 'Gantt', name: 'Gantt' },
        { value: 'Workflow', name: 'Workflow' },
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixs: [{ value: "closed", name: "closed:   ISSUES has been processed" }],
    customIssuePrefixsAlign: "top",
    emptyIssuePrefixsAlias: "skip",
    customIssuePrefixsAlias: "custom",
    allowCustomIssuePrefixs: true,
    allowEmptyIssuePrefixs: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: ""
}
